#
# TABLE STRUCTURE FOR: posts
#
USE vk;
DROP TABLE IF EXISTS `posts`;

CREATE TABLE `posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `community_id` int(10) unsigned DEFAULT NULL,
  `head` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `body` text COLLATE utf8_unicode_ci NOT NULL,
  `media_id` int(10) unsigned DEFAULT NULL,
  `is_public` tinyint(1) DEFAULT 1,
  `is_archived` tinyint(1) DEFAULT 0,
  `views_counter` int(10) unsigned DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (1, 4, 2, 'omnis', 'Aliquam molestias laboriosam quia et expedita. Laboriosam vitae modi suscipit veniam itaque sit. Soluta illum reprehenderit doloribus doloribus et eum.', 3, 0, 0, 123409295, '1991-03-22 17:35:56', '2005-05-15 14:46:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (2, 3, 0, 'fugiat', 'Sit ut suscipit ut delectus rem rem. Voluptatibus et earum quas delectus commodi. Quia impedit ipsam quis quia ut ut. Ratione autem sapiente repellendus labore.', 2, 1, 1, 62672, '2009-07-28 00:21:23', '2014-04-05 16:22:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (3, 7, 0, 'voluptate', 'Corporis officia dolor eius et. Commodi rerum minima veniam corrupti accusantium quia modi. Aut qui possimus odit fugit exercitationem similique molestiae sit. Qui eum cupiditate quo rerum ea omnis earum.', 0, 0, 1, 9, '1996-03-28 21:59:29', '2010-09-29 18:16:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (4, 9, 1, 'eveniet', 'Natus sit temporibus dolor quis deserunt voluptate tempora sed. Quam repellendus mollitia voluptatem nisi ducimus culpa ipsam voluptatibus. Voluptas culpa incidunt est sed rerum id reiciendis beatae. Nemo pariatur vitae delectus. Perspiciatis ipsum molestiae sunt minus velit libero velit perferendis.', 6, 0, 0, 159224870, '2005-06-22 23:01:13', '2002-08-07 00:30:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (5, 6, 1, 'corrupti', 'Molestias qui voluptatem sapiente dolor nihil excepturi consequuntur. Maiores qui optio minima odit. Esse dolor magni at tempore nihil. Reprehenderit reprehenderit aperiam tenetur quo iusto numquam nisi.', 0, 0, 1, 0, '1970-05-16 13:55:22', '2000-12-02 11:38:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (6, 0, 4, 'maiores', 'Ut maiores quis est quia aliquam illo. Corporis delectus nemo id quidem sapiente doloribus quia. Rerum voluptas iusto voluptatum et non autem.', 4, 1, 1, 0, '2000-04-24 22:11:40', '1983-12-19 17:33:07');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (7, 1, 1, 'animi', 'Minima voluptas voluptatem et sit quo vel fugit. Est ipsam commodi consequatur accusantium quo ullam.', 9, 1, 1, 6857785, '1970-08-21 07:59:16', '1973-06-14 15:04:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (8, 6, 2, 'accusantium', 'Voluptatem recusandae nam voluptate aut. Ipsam expedita ut consequatur sunt eligendi. Ducimus quasi doloremque quia. Recusandae nam cupiditate aut id ipsam rerum temporibus. Sunt recusandae sit veritatis omnis.', 4, 1, 1, 62837, '1977-10-21 02:10:16', '1972-10-01 08:02:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (9, 0, 1, 'voluptatem', 'Voluptatem dolor ad aut nisi. Aut ut error velit reiciendis iure debitis praesentium. Eaque sit adipisci nulla aut maxime.', 7, 0, 1, 765404, '2008-05-28 18:36:31', '1971-09-17 17:03:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (10, 1, 3, 'cum', 'Iste minus autem occaecati dolor. Eos autem nisi accusamus inventore beatae quia.', 6, 1, 0, 518262297, '1986-07-09 13:08:03', '2012-08-30 05:20:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (11, 2, 8, 'similique', 'Ea eius et cum non maiores occaecati. Repellat voluptatibus veritatis ut aut ullam minus id. Est sit et consequuntur sint accusamus sapiente voluptates. Tempore blanditiis aliquam laboriosam eos voluptatibus non sed. Aut reiciendis rem nulla.', 7, 0, 1, 666, '2018-08-28 16:05:06', '1989-04-01 08:42:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (12, 9, 0, 'quos', 'In nobis dolorem enim numquam. Consequatur labore quo sint sint hic enim explicabo. Numquam illo aut illum consequuntur molestias sit expedita.', 0, 0, 1, 406576, '1975-09-26 23:35:38', '2003-05-19 14:12:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (13, 0, 5, 'cum', 'Nihil eum accusantium atque rerum sit quasi fugiat. Sed quia nostrum neque debitis voluptas enim corporis. Nemo et velit voluptatem distinctio sint officiis quae velit.', 9, 1, 0, 3, '1973-12-03 15:52:49', '1997-01-03 08:29:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (14, 9, 5, 'rerum', 'Sequi reprehenderit eveniet tempora quidem possimus. Enim consequuntur vel atque sit voluptatem impedit et. Ut consequuntur at incidunt laboriosam aperiam. Praesentium ut impedit beatae id voluptatem similique excepturi.', 5, 1, 0, 3849603, '1997-09-22 21:52:46', '2001-04-21 00:20:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (15, 2, 1, 'expedita', 'Ratione sunt tempora qui quod. Quia quod qui velit quod debitis excepturi. Dicta doloremque cupiditate dolorum et consequuntur cumque. Doloremque quia commodi non nostrum.', 2, 1, 1, 1758, '1994-07-18 09:24:02', '2006-02-01 03:54:37');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (16, 4, 0, 'quo', 'Dolorem ducimus incidunt sit aperiam rerum error. At ratione quia consequatur porro in voluptatem assumenda. Laborum quia dolorum officia non tempora veritatis. Ducimus ut nisi enim aliquid velit et nobis ut. Voluptas animi voluptatem delectus architecto id modi voluptatem.', 1, 0, 1, 76, '1996-09-11 10:52:56', '2020-05-14 04:16:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (17, 6, 0, 'animi', 'Voluptas ut excepturi voluptate esse quaerat nobis iusto. Architecto perspiciatis autem velit omnis et. Animi aut sed est ullam ad. Eum ut natus architecto sint architecto accusantium.', 8, 0, 1, 30546, '2010-06-16 09:01:50', '1971-04-15 07:53:45');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (18, 6, 2, 'consequatur', 'Quidem aperiam est ut. Qui blanditiis est dolorum exercitationem ut non. Aperiam vero fugiat odio recusandae accusamus rerum dicta. Aliquam et esse rerum distinctio cum nobis aut natus.', 8, 0, 0, 0, '2013-05-26 15:37:51', '1987-07-31 18:46:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (19, 9, 3, 'dicta', 'Occaecati porro repudiandae est quia consectetur iure sapiente. Voluptate ad accusantium veniam deleniti enim sapiente eius voluptatem. Eos iusto animi voluptate autem.', 4, 1, 0, 88672540, '2004-12-30 11:38:21', '1970-02-24 14:33:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (20, 3, 9, 'sint', 'Dicta et non ducimus esse. Rerum doloremque aut vel commodi animi officia totam et. Veniam dolores ut nisi quasi aperiam tenetur consequatur et. Provident voluptas facilis maiores repellendus voluptatem repellendus.', 1, 0, 1, 24, '1983-07-02 05:14:18', '2015-06-23 08:52:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (21, 1, 7, 'et', 'Aut qui sit quod autem qui aut et ad. Explicabo facere amet nemo reprehenderit.', 0, 0, 1, 545, '1993-12-25 12:57:00', '2005-03-30 07:55:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (22, 9, 9, 'qui', 'Natus sed exercitationem illum quae placeat doloribus. Repudiandae maiores nam at voluptatem consequatur enim. Inventore eius est sit nam repudiandae quod quibusdam. Corrupti reiciendis quibusdam voluptatibus.', 3, 1, 0, 4719080, '2015-06-23 13:14:18', '2002-02-09 23:23:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (23, 8, 1, 'repellat', 'Ducimus quo ipsa aspernatur velit eum. Architecto magnam repellendus aliquam. Numquam laborum praesentium non sit illo iusto molestiae labore. A quia et vel magnam perferendis.', 7, 0, 1, 258, '2015-09-10 00:51:53', '1974-07-19 12:18:36');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (24, 8, 0, 'cupiditate', 'Corrupti eum quisquam quisquam deserunt ut sit totam aut. Reiciendis ad quasi et iste quod cum. Voluptatem dolorem nam labore dolores numquam dolorem non. Culpa expedita architecto animi deleniti sed error.', 2, 0, 1, 4969110, '2018-07-20 02:35:52', '1981-06-23 13:48:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (25, 7, 2, 'maiores', 'Veritatis aut dolorem ut maiores. Omnis quos assumenda quis sapiente est. Dicta quia et voluptatem et.', 6, 0, 1, 0, '2018-04-12 02:44:26', '1992-05-16 21:55:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (26, 5, 2, 'ut', 'Et aut quasi quis officiis. Dolorem dolor eum et dolorum. Distinctio distinctio molestiae pariatur dolorum et quasi sint.', 0, 1, 1, 281, '1996-10-16 01:09:57', '2003-10-02 21:16:14');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (27, 0, 5, 'eligendi', 'Sapiente ipsum quam iure. Molestias occaecati et aut quasi. Dolores quis laboriosam id quisquam et.', 8, 0, 1, 3, '1990-05-23 21:24:22', '1978-11-10 02:21:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (28, 9, 4, 'voluptas', 'Qui facilis earum reiciendis. Minus optio dolor et.', 7, 0, 1, 6314, '1981-08-25 11:14:55', '1998-03-12 14:21:47');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (29, 9, 7, 'explicabo', 'Excepturi sint dolorem et sed nisi ut. Esse laudantium molestiae qui suscipit molestiae nobis. Debitis et debitis assumenda quia maiores dicta vero.', 9, 1, 1, 5, '1970-01-10 19:43:25', '1973-10-12 10:55:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (30, 0, 9, 'qui', 'Pariatur error eligendi molestias alias ut sit sunt. Nulla ipsum nostrum culpa delectus ullam quis. Nam dolores et nisi et ea qui. Voluptatem eligendi aut et ea.', 1, 1, 0, 979154, '2011-03-23 17:55:09', '1977-07-23 10:50:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (31, 6, 6, 'ea', 'Libero et explicabo commodi ipsam non aspernatur rerum. Est praesentium architecto sit ut sint vel quaerat. Possimus reiciendis omnis nobis animi id dolor mollitia.', 5, 0, 0, 0, '2015-04-22 15:14:27', '1976-07-25 16:36:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (32, 7, 4, 'necessitatibus', 'Nulla dolor asperiores dolores repudiandae est amet. Quod unde quasi odit necessitatibus corrupti. Incidunt aspernatur possimus rerum voluptatibus.', 7, 0, 1, 25767105, '2017-02-09 20:13:04', '2014-06-03 09:38:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (33, 3, 4, 'animi', 'Sunt sed asperiores maxime enim et nostrum facilis. Dolores delectus voluptas illo molestias ex. Excepturi non id omnis rerum. Nam tempore necessitatibus maxime facere qui.', 6, 0, 1, 9878755, '1984-04-26 20:25:34', '2019-11-09 13:01:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (34, 7, 8, 'hic', 'Facere aliquid pariatur nihil. Sit aut voluptatibus commodi et. Quia in dolor non tempore dicta quo voluptatibus. Aut id aspernatur aut similique magnam expedita necessitatibus.', 2, 0, 1, 926728168, '1988-01-26 13:40:23', '1987-11-24 21:02:37');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (35, 9, 8, 'perferendis', 'Aliquam et eos aperiam. Ea tenetur voluptatem et iste laborum laudantium esse. Odit perferendis explicabo rerum eos et animi. Consectetur corporis et possimus itaque tenetur consequatur quisquam.', 4, 1, 1, 487604, '1992-01-23 14:33:12', '1999-03-13 11:14:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (36, 3, 0, 'id', 'Et dicta doloribus et aliquam ratione doloribus voluptas et. Quisquam libero dolores velit neque.', 6, 1, 1, 1760, '1982-06-12 21:38:55', '1971-11-03 11:15:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (37, 2, 2, 'nisi', 'Error aut dolor debitis ducimus rerum est assumenda nostrum. Et dolor nam aliquid mollitia. Dolorem voluptas molestiae qui voluptates rerum. Tempore necessitatibus laboriosam autem facere ut. Labore corporis fugiat earum iusto.', 7, 0, 0, 9, '1998-06-25 12:34:01', '2016-05-09 14:37:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (38, 9, 0, 'voluptate', 'Quibusdam ratione quas occaecati esse pariatur natus. Ab vitae quam amet. Reprehenderit ipsa reprehenderit qui similique delectus.', 4, 0, 1, 530759, '1994-12-06 18:50:10', '1989-07-22 14:15:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (39, 5, 0, 'facilis', 'Debitis aut quaerat id laboriosam delectus dicta. Impedit ut illo quas at. Debitis quis provident maiores magnam et sint deleniti asperiores.', 7, 0, 0, 687, '1985-10-07 00:45:56', '2011-03-06 21:27:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (40, 3, 3, 'consequatur', 'Reiciendis nemo praesentium vel. Maiores est et earum facere et delectus. Dolores doloribus magni consequatur.', 3, 0, 0, 4, '2008-02-12 17:11:31', '1986-08-17 14:06:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (41, 5, 0, 'molestias', 'Error facilis architecto illum nam. Expedita minus modi ipsum culpa molestiae ad. Consequatur voluptates quia sed quae et fugit eligendi modi. Dignissimos excepturi deleniti adipisci dolores. Necessitatibus et unde recusandae nisi veniam.', 4, 0, 0, 59948, '2005-06-07 18:25:15', '1998-03-17 00:42:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (42, 3, 3, 'occaecati', 'Enim tenetur quo voluptatibus vel suscipit alias sed. Tempore iste error quos. Ipsum est est minus ut harum.', 4, 0, 0, 356585, '2010-02-22 20:33:49', '1981-02-24 07:16:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (43, 0, 2, 'odit', 'At placeat numquam qui in voluptatem est consequatur. Nam voluptas ipsa molestias accusantium beatae ducimus. Impedit a esse recusandae et aspernatur qui perferendis. Voluptas illum eligendi rerum voluptatum excepturi. Est debitis adipisci rerum reprehenderit omnis velit.', 7, 0, 1, 240714, '1988-11-23 21:26:48', '1985-07-22 12:49:36');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (44, 2, 0, 'corrupti', 'Et sunt officiis nobis est et. Consequatur eos optio aliquid ipsam eveniet. Rerum maxime sunt ut distinctio laboriosam blanditiis ratione.', 3, 0, 1, 51, '2016-10-17 12:17:46', '2003-12-21 23:38:47');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (45, 4, 6, 'dolores', 'Unde laborum optio est vel hic eligendi et nesciunt. Aut voluptatum nemo porro cumque mollitia. Ipsa eaque a quam. Adipisci qui excepturi et eum autem aut quae.', 3, 1, 1, 9, '2008-07-10 21:36:58', '2014-09-05 22:15:36');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (46, 6, 3, 'omnis', 'In ea facilis necessitatibus aperiam alias. Consequuntur atque et molestias asperiores dicta. Ex placeat et et voluptas alias. Eveniet aperiam voluptas dicta quasi voluptas.', 8, 0, 0, 0, '1995-12-06 17:47:34', '2018-10-15 07:19:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (47, 4, 1, 'doloribus', 'Fuga officia eos reprehenderit ducimus eum. Et facere maiores maiores tempora ipsam.', 6, 0, 1, 5157, '1983-02-14 14:29:43', '1994-01-29 15:44:39');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (48, 3, 9, 'porro', 'Rerum eveniet ut sunt cumque quo id placeat sed. Eligendi illo nihil eaque expedita eum. Iusto animi eum consequatur eos amet vero reiciendis.', 8, 0, 0, 54383, '1993-06-20 15:52:24', '1978-10-04 08:51:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (49, 4, 8, 'odit', 'Dicta quos aspernatur reiciendis corrupti. Dolor saepe qui reiciendis fugiat aut dicta iste.', 8, 1, 1, 0, '1996-08-25 12:13:42', '1993-05-28 19:39:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (50, 9, 8, 'commodi', 'Consequatur odio enim ipsa et recusandae ea. Enim et aliquam quae voluptatibus. Itaque voluptas repudiandae vitae possimus.', 4, 0, 0, 36296, '2004-03-13 17:13:40', '1977-10-22 20:52:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (51, 1, 4, 'sint', 'Quia optio et et qui architecto rerum. Exercitationem sequi voluptate nihil. Quis incidunt sit voluptatum debitis ipsa voluptas rerum. Expedita et unde rerum autem sequi sit minima.', 7, 1, 0, 797610962, '2003-03-22 09:43:11', '1994-02-06 06:13:09');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (52, 3, 7, 'harum', 'Quo porro occaecati ut voluptas. Esse modi sit quisquam fugit modi.', 4, 0, 0, 2103188, '2010-01-14 11:20:00', '2010-10-01 03:57:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (53, 0, 2, 'voluptas', 'Quidem repellendus adipisci sed at nihil mollitia. Quis voluptas odio minus quaerat. Quibusdam quia quos molestiae aliquid libero non. At velit voluptatem illum cumque sit.', 3, 0, 0, 5, '1991-07-24 18:13:21', '1982-04-21 22:56:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (54, 7, 3, 'maiores', 'Error consequatur debitis iste et et ipsum. Quidem est et sint eos quas explicabo.', 1, 1, 1, 581610384, '1983-01-24 18:10:06', '2012-10-23 09:42:55');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (55, 6, 2, 'animi', 'Dolorem quia ad voluptatem iure quia aut molestias nulla. Voluptate eius cupiditate eveniet reiciendis cupiditate et nam itaque. Id est ab sed in aut error soluta.', 6, 1, 1, 941, '1970-03-26 11:32:55', '2014-08-06 18:53:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (56, 9, 1, 'neque', 'Sint vero omnis reprehenderit accusamus. Dolor recusandae fugiat quas laboriosam id. Dolorem occaecati et debitis amet at. Perspiciatis aut aspernatur facere est ut est sed vel.', 1, 1, 0, 9, '2007-12-22 21:17:24', '1993-05-25 15:13:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (57, 8, 1, 'commodi', 'Deleniti vel nihil id minus. Ea maxime eligendi sed unde. Ducimus omnis saepe aliquam architecto impedit a mollitia. Nam in natus perferendis libero.', 3, 0, 1, 344336, '2016-05-14 16:20:41', '2015-04-07 18:59:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (58, 3, 5, 'fugiat', 'Ut voluptatem asperiores debitis laborum veritatis. Optio eum et eius cumque. Iste a reprehenderit laboriosam laborum voluptatem.', 5, 0, 0, 717715, '1984-05-06 07:25:27', '2008-12-20 08:36:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (59, 7, 1, 'ut', 'Perspiciatis similique eveniet repellendus rem fugiat accusantium voluptatem. Velit dignissimos et nihil saepe laborum qui minima temporibus. Saepe expedita autem ut eius et et ullam.', 0, 0, 1, 23, '1979-08-15 00:49:46', '1983-06-17 21:24:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (60, 8, 0, 'est', 'Provident necessitatibus in ab at. Aspernatur blanditiis eveniet maiores doloribus culpa. Necessitatibus voluptas consequatur maxime consequuntur dolor. Possimus veniam et aspernatur molestiae nobis est commodi.', 2, 0, 1, 31085144, '2005-12-12 06:07:12', '1988-12-22 03:42:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (61, 0, 5, 'sit', 'Eum ut dolor rerum qui qui eius veniam. Sunt dolores non facere saepe suscipit rerum eius error. Quod maiores officia reiciendis et veniam cupiditate voluptate. Eveniet voluptatem delectus esse quo velit.', 1, 1, 1, 874, '1993-07-23 18:58:54', '2020-02-02 18:17:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (62, 0, 4, 'qui', 'Dolores quidem in eos. Exercitationem nihil facere nesciunt rerum enim. Quae assumenda ipsa expedita est et et consequatur sed. Esse sunt dolor magni.', 0, 0, 1, 666107, '1978-12-10 08:26:52', '1971-04-06 21:14:50');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (63, 8, 1, 'voluptatem', 'Dolor quo sit nostrum voluptatum eos natus. Saepe rem eveniet maxime id qui sit totam.', 3, 0, 0, 5025901, '2016-11-15 10:40:05', '1990-01-09 14:38:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (64, 7, 0, 'voluptatem', 'Quaerat culpa quaerat delectus. Et fugit soluta velit nihil dolor.', 4, 0, 1, 7560, '1987-06-17 19:25:18', '1974-07-13 15:07:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (65, 3, 3, 'totam', 'Excepturi doloremque omnis assumenda consectetur pariatur doloribus sint. A sunt sit deleniti porro. Numquam ipsa magnam quia ipsam sunt cum voluptatem.', 2, 0, 1, 4160929, '1988-04-08 09:40:50', '1976-04-01 07:20:20');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (66, 7, 6, 'beatae', 'Et sed molestiae doloremque commodi libero perspiciatis. Maxime impedit assumenda sit et aliquam eos.', 9, 0, 1, 50955, '1971-08-27 12:03:41', '2004-11-12 16:54:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (67, 9, 8, 'qui', 'Illum non consectetur eum corrupti quia dolores. Placeat voluptatem ducimus quia aliquam. Aliquam nesciunt dolores sint quam non inventore cumque. Cupiditate nam repellendus sed ut reiciendis provident non sit.', 1, 1, 0, 846406281, '1987-01-21 17:15:51', '2011-04-28 01:37:10');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (68, 6, 5, 'aperiam', 'Voluptate delectus asperiores delectus et autem consequuntur. In est est voluptas accusantium ut ex illo cum. Aut repudiandae quia autem ducimus optio porro velit.', 5, 0, 1, 899465, '1981-08-12 01:07:24', '2003-01-30 13:11:21');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (69, 2, 1, 'cumque', 'Accusantium cumque aut est. Aut tenetur nesciunt sunt et alias eum voluptas in. Autem rem ducimus voluptatem. Consequatur modi sit ut eos enim. Ut consequatur sed amet amet.', 0, 1, 1, 502829548, '1970-03-31 04:59:15', '1978-09-07 12:37:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (70, 7, 7, 'beatae', 'Magnam earum accusantium nulla. Non magni aut iste debitis.', 6, 1, 1, 2, '1982-01-30 08:57:45', '1993-08-19 05:41:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (71, 0, 6, 'voluptate', 'Accusantium qui ea accusantium delectus quasi et beatae. Tenetur nam fugiat similique quidem ex. Sunt enim dolores et ratione mollitia quam enim quia.', 3, 1, 0, 6, '1977-01-23 13:58:44', '2017-05-22 06:35:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (72, 8, 5, 'blanditiis', 'Praesentium atque nihil est aut ipsam veniam. Fugit omnis cupiditate natus id. Corrupti officia voluptatem quidem vel distinctio ab.', 3, 1, 1, 403954, '1979-03-18 07:58:26', '2000-02-09 16:46:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (73, 7, 7, 'distinctio', 'Sapiente eos et in esse. Voluptas quia placeat nihil enim blanditiis dolor error. Provident reprehenderit laborum ipsam animi enim.', 9, 1, 0, 20727, '1970-12-12 10:55:59', '1992-02-24 12:10:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (74, 3, 7, 'animi', 'Nam maxime voluptatum mollitia. Et qui dolorum ab. Provident aperiam explicabo quis a omnis minus. Et et a accusamus. Sed velit saepe accusantium.', 9, 1, 0, 7, '1999-12-22 06:45:24', '1981-08-19 03:42:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (75, 1, 7, 'vel', 'Dolores quod in velit eligendi velit. Excepturi distinctio quaerat vero nemo molestiae qui. Dolores quo aut commodi ipsa eos enim. Nam non ut architecto earum ipsum voluptates cupiditate.', 4, 1, 1, 504930108, '1997-01-24 21:44:02', '2007-11-08 12:08:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (76, 0, 0, 'ullam', 'Qui similique reiciendis neque illum. Pariatur non aut in blanditiis.', 5, 0, 0, 3102, '1974-06-29 02:41:52', '1993-02-25 09:15:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (77, 8, 9, 'in', 'Voluptates numquam cupiditate cupiditate non placeat distinctio. Omnis aliquam illo aut id repellendus. Modi eveniet quas voluptatem vel cum. Unde illo quia sed fugit totam.', 0, 1, 1, 931051363, '1995-01-08 21:54:19', '2009-05-24 10:10:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (78, 9, 5, 'tempore', 'Sit voluptatibus illo esse ipsum et possimus. Eos porro sed omnis modi quia atque. Est voluptatum occaecati autem et optio numquam harum. Numquam non autem quae consequuntur quia.', 3, 1, 1, 4924, '2009-04-25 00:26:12', '2005-11-20 19:57:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (79, 8, 6, 'doloremque', 'Quod esse asperiores commodi ipsa mollitia occaecati numquam sapiente. Sed est assumenda sint voluptatem iste. Facere aperiam omnis necessitatibus aspernatur earum sed et. Eligendi sequi aut quia corrupti aliquam labore excepturi aut. Odio aliquid porro possimus ea recusandae quae veritatis.', 0, 1, 1, 5, '1973-05-10 10:29:44', '2019-07-26 15:20:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (80, 4, 8, 'velit', 'Rem sapiente corporis quia est culpa. Ea corporis molestiae suscipit totam. Unde reprehenderit odit sapiente eveniet dignissimos et enim. Autem est hic sit doloribus nulla cupiditate. Eum quaerat earum quis et esse aut aut in.', 2, 1, 0, 293389, '2002-12-13 05:35:28', '1984-02-02 17:15:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (81, 1, 2, 'ut', 'Iste ratione saepe nobis molestias sit omnis quaerat. Eaque nesciunt quo aut quisquam. Et rerum minus et non. Occaecati in ex velit et nihil dolor.', 8, 0, 1, 8197, '1977-04-25 21:19:51', '1996-12-01 06:53:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (82, 8, 0, 'tempora', 'Animi ut porro asperiores cum. Minima est magni nihil est. Cum hic numquam unde libero quod atque illum. Est qui qui maxime sit qui.', 1, 1, 1, 0, '2002-10-01 20:05:10', '2006-01-27 16:08:14');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (83, 6, 0, 'dignissimos', 'Sit rerum aut recusandae est placeat et. Et fugit sint voluptas natus. Corrupti et nam maiores possimus.', 8, 0, 0, 67, '1986-08-15 15:30:44', '1982-10-13 16:28:53');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (84, 9, 5, 'molestiae', 'Architecto adipisci excepturi modi quibusdam amet cumque soluta voluptatem. Sit vitae aspernatur qui ut laboriosam est. Delectus sint error distinctio omnis ipsam dolore ipsam. Eos nihil corrupti veniam voluptas. Ducimus porro possimus omnis facere ex.', 7, 1, 1, 491692, '1990-11-25 11:27:57', '2008-07-29 07:16:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (85, 8, 6, 'accusantium', 'Illo ut autem hic et earum ex autem fugiat. Vitae pariatur et earum ipsum quae quas. Repellendus qui incidunt consequatur rerum.', 5, 1, 0, 68, '2017-03-11 02:45:36', '1980-05-31 18:18:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (86, 8, 3, 'beatae', 'Saepe sapiente commodi illum. Aliquam consequuntur nihil similique eum dicta vel consequatur. Incidunt aut possimus eos hic sit.', 8, 1, 0, 781604167, '1995-09-09 22:44:08', '1997-07-19 15:42:09');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (87, 6, 6, 'pariatur', 'Quidem accusantium molestiae corrupti ut voluptas porro. Quasi ab quisquam harum quisquam voluptatum. Fugiat fugit assumenda eos eius dignissimos quibusdam sequi sit.', 7, 0, 0, 66157, '1972-07-10 03:52:14', '1990-03-31 21:25:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (88, 2, 8, 'eum', 'Omnis cum et tempora voluptatem cum. Modi aut nam veniam consequuntur. Praesentium optio exercitationem autem dolore.', 5, 0, 1, 7142538, '1984-11-25 17:40:29', '1986-08-19 19:08:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (89, 6, 7, 'quidem', 'Ut ex debitis et reprehenderit corporis quis. Omnis minus amet qui animi consequatur magnam consectetur. Veniam consequatur nesciunt ut quisquam officiis.', 9, 1, 1, 7181, '2009-03-21 14:57:31', '2019-07-28 11:24:09');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (90, 6, 9, 'maxime', 'Aut dolore dolores optio. Ullam recusandae fugit ut velit minima sint et. Similique corporis vero perspiciatis nihil. Quaerat eos hic earum accusantium fuga quos consequatur.', 1, 0, 0, 417950835, '1970-01-23 20:21:51', '1987-04-26 23:34:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (91, 8, 7, 'quam', 'Ad consectetur repellat voluptatum ut culpa qui culpa. Maiores quidem deserunt delectus molestiae doloribus eveniet reprehenderit eius. Beatae unde optio quia sunt. Accusantium sint ut et repellendus et.', 1, 1, 0, 196, '2006-11-30 06:44:17', '1978-05-25 16:05:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (92, 1, 0, 'qui', 'Est id nam perspiciatis eos illum. Dignissimos nisi et enim eaque enim. Inventore iste et consectetur harum. Nihil perferendis molestias itaque aut facere et culpa.', 7, 1, 1, 14583, '1983-03-27 23:16:22', '1995-11-30 08:15:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (93, 9, 9, 'non', 'Incidunt qui voluptatum aut fuga ut assumenda est. Voluptas illum eum temporibus id ut molestiae veritatis. Atque molestias expedita cum voluptate.', 0, 0, 1, 0, '2006-12-23 22:04:41', '1977-04-11 12:39:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (94, 8, 0, 'minima', 'Earum praesentium repellat maxime atque itaque quia quia magnam. Explicabo dolore aut quaerat qui quia. Et sit cumque dolor sed ad vitae.', 6, 0, 0, 83, '1983-03-13 22:28:06', '1981-07-21 20:07:47');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (95, 0, 0, 'magnam', 'Nesciunt odio adipisci illo rerum. Id tenetur debitis corporis ut. Et accusamus pariatur aliquid ea quod. Perferendis sint id tempora quasi eum nisi voluptas.', 6, 0, 0, 636, '2003-11-17 19:30:47', '1992-10-09 12:48:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (96, 1, 8, 'temporibus', 'Suscipit repellendus totam ut quasi. Voluptatem cupiditate totam sint dolor ad voluptatem. Et molestias et iusto qui illo. Assumenda minima quibusdam consequatur doloremque animi labore.', 8, 1, 1, 0, '1970-12-29 22:08:31', '2009-08-06 21:25:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (97, 3, 2, 'qui', 'Amet quis consectetur delectus sed sunt et. Aut recusandae dolores dolores. Possimus excepturi praesentium nisi quibusdam dolor qui soluta. Ut beatae aut sed repudiandae corporis deleniti assumenda. Omnis non nihil animi omnis quibusdam velit.', 8, 0, 0, 908630310, '1975-08-27 09:03:02', '1992-01-03 21:15:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (98, 1, 4, 'vero', 'Nemo sed voluptatem nisi distinctio officiis occaecati. Omnis explicabo ipsum quos placeat adipisci.', 8, 0, 1, 81415231, '2013-12-26 00:03:44', '1990-11-17 17:22:39');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (99, 6, 1, 'quas', 'Consectetur accusantium culpa autem quo sit in qui dolor. Est necessitatibus assumenda similique occaecati cumque corrupti odio dolorem. Et recusandae totam sed quo autem nisi voluptas.', 5, 1, 1, 0, '2004-01-16 11:25:39', '1995-07-27 06:44:47');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (100, 5, 2, 'maiores', 'Eos maxime error dolor non illum. Dolorem sunt fuga esse autem cumque. Aliquam et hic corporis ut et nam recusandae excepturi. Reiciendis ut labore architecto animi dolorum.', 4, 0, 0, 5748, '2019-09-20 16:18:13', '2012-05-12 22:39:50');


